### ISSUE TITLE
GUI timezone config

### ISSUE THREAD

**Issue by pepa65** [dmedvinsky/gsimplecal#25]
gsimplecal has been my favorite calendar applet for many years. There is no other one better. Not everybody understands the importance of displaying time in different time zones being integrated in the calendar application.

It would be so great if the timezones could be configured with a GUI, so more people would feel comfortable using it. I once made something in Zenity, but it would be neat if it could just be an integral part of gsimplecal.

**Comment by dmedvinsky** [comment]
Gsimplecal aims for minimalism and its target audience is the kind of people who enjoy minimalism in all the areas, like distros, WMs, editors etc. Usually this means that these folks build their environment with their own hands and are not alien to editing their config files with the text editors.

So, I don't think making a full-blown GUI configurator for a one-time configuration is worth it. In pretty much any application, and especially in one that specifically aims for minimalism.
