### ISSUE TITLE
Time zones

### ISSUE THREAD

**Issue by surruk51** [dmedvinsky/gsimplecal#27]
I am trying to use gsimplecal as a quick and easy way of showing the time in a number of different zones. The simplicity and layout is ideal, but apart from local time (which I don't need as its on my desktop anyway) whatever i put in clock_tz I seem to get UTC

A few examples to help me out would be great
At present I am trying to use BST, EDT and CDT

**Comment by dmedvinsky** [comment]
Generally, you should find the matching zones in `/usr/share/zoneinfo` files and then use those as the `man timezone` says, i.e. by specifying them as `:UTC`, `:Europe/London`, etc.

For your specific zones that would be

BST = :Europe/London (not sure about this, but as far as Google lead me to believe, London uses BST)
EDT = :US/Eastern
CDT = :US/Central

In terms of gsimplecal config it would like something like this:

```
clock_label = UTC
clock_tz = :UTC
clock_label = Local
clock_tz =
clock_label = BST
clock_tz = :Europe/London
clock_label = EDT
clock_tz = :US/Eastern
clock_label = CDT
clock_tz = :US/Central
```

Does this work for you?

**Comment by surruk51** [comment]
Thank you for the quick response. Your suggestions worked well.

I was confused because the example in the default config in the man 
pages showed only UTC which is the same in short code and long.

Maybe something like this in the man page would make it clear to dummies 
like me:
===================
clock_tz parameter locates the relevant timezone file which is held in 
the sub-directory
      /usr/share/zoneinfo/{continent}/{time zone area}
where {continent} and {time zone area} represent the various valid 
continents and the time zone areas within them.
eg:
for /usr/share/zoneinfo/Europe/London
clock_tz = :Europe/London

for /usr/share/zoneinfo/US/Eastern
clock_tz = :US/Eastern
=====================

Thanks gain for your help

Chris.

**Comment by dmedvinsky** [comment]
Added more examples and clarified the setting a little in the man page: 2dc6bbab18f51ee2ad0eb33f9b8ff48db849f95e
