### ISSUE TITLE
Two instances overlapping each other

### ISSUE THREAD

**Issue by dglava** [dmedvinsky/gsimplecal#29]
Sometimes when starting gsimplecal (via tint2), it opens twice. After that it's impossible to close it by deselecting the window (clicking anywhere else).

Most of the time this got triggered with a single click, but it could also be due to my faulty mouse which occasionally double clicks very fast. To reproduce this, I kept clicking on the area in tint2 which opens gsimplecal and I was able to reproduce it. Once the bug occurs, there are 2 instances of gsimplecal running.

Is this a gsimplecal bug or perhaps something on tint2's end?
Here's a video of the bug:
https://webmshare.com/dQVNV

**Comment by Kurgol** [comment]
I just had this exact same issue, and it does crop up from time to time - though mine was from manually clicking fast, rather than launching from tint2 etc.

    $ ps -ef | grep gsimplecal
    andy     13062  1172  0 14:06 ?        00:00:00 /bin/sh -c gsimplecal
    andy     13063 13062  0 14:06 ?        00:00:00 gsimplecal
    andy     13299  2201  0 14:14 pts/0    00:00:00 grep gsimplecal
    andy@host:$ kill -9 13063 13062

Cleared it for me, but it's frustrating when it occurs.

**Comment by dglava** [comment]
I haven't had this issue in a while. I think this was due to my faulty mouse (double clicking) and the panel allowing two fast executions. I guess there's not much gsimplecal can do, other than to prevent 2 instances of itself from running, but that seems unnecessary.
