### ISSUE TITLE
Just to say thank you!

### ISSUE THREAD

**Issue by cjbarroso** [dmedvinsky/gsimplecal#33]
I'm using the app because I needed a lightweight, look-only calendar on my ion3 setup. Using it like a year or so, and it's perfect for my use case. Thank you!

**Comment by dmedvinsky** [comment]
Awesome. Thanks for letting me know. Unfortunately, I don't really use it myself at the moment, as I currently have to use MacOS, so I don't quite have motivation to work on it. But it's really great to know that it still works for someone.
