### ISSUE TITLE
start of week not changing

### ISSUE THREAD

**Issue by KaffeMyers** [dmedvinsky/gsimplecal#34]
Hi!

Changing my DIY desktop environment and bumped into tint2 + gsimplecal. Only immediate caveat I found was that I could not change the start of week, despite setting `force_lang = en_GB.utf8` (also tried `force_lang = en_GB.UTF-8`) in `~/.configure/gsimplecal/config` as described in the man page. All other options I've tried have worked as intended. 
Installed via apt repo, Debian 9.
Any ideas?

**Comment by mjs** [comment]
Did the configuration path you mentioned isn't quite right. It should be: `~/.config/gsimplecal/config` (i.e. `.config` not `.configure`). Could that be the problem?

**Comment by mjs** [comment]
Using `force_lang = en_GB.utf8` works for me using version 2.1

**Comment by KaffeMyers** [comment]
I'll check it out once I'm back at work!  That'll be in September.  :P

**Comment by k0rn1** [comment]
It also doesn't work for me

Current config

```
show_calendar = 1
show_timezones = 1
mark_today = 1
show_week_numbers = 1
close_on_unfocus = 0
external_viewer = sunbird -showdate "%Y-%m-%d"
clock_format = %a %d %b %H:%M
force_lang = en_GB.utf8
mainwindow_decorated = 0
mainwindow_keep_above = 1
mainwindow_sticky = 0
mainwindow_skip_taskbar = 1
mainwindow_resizable = 0
mainwindow_position = none
mainwindow_xoffset = 0
mainwindow_yoffset = 0
clock_label = UTC
clock_tz = :UTC
clock_label = Local
clock_tz =
```

**Comment by KaffeMyers** [comment]
What a scatterbrain I am, I never got back to you.

Anyway, the problem persists for me to this day. 

```
$ pwd
/home/kaffe/.config/gsimplecal
$  gsimplecal --version
gsimplecal 2.1
$ cat config 
show_calendar = 1
show_timezones = 1
mark_today = 1
show_week_numbers = 1
close_on_unfocus = 1
external_viewer = sunbird -showdate "%Y-%m-%d"
clock_format = %a %d %b %H:%M
force_lang = en_GB.utf8
mainwindow_decorated = 0
mainwindow_keep_above = 0
mainwindow_sticky = 0
mainwindow_skip_taskbar = 1
mainwindow_resizable = 0
#mainwindow_position = none
mainwindow_xoffset = -25
mainwindow_yoffset = 30
```

**Comment by merwok** [comment]
Does anything change if you use `en_GB.UTF-8` rather than `.utf8`?

**Comment by dmedvinsky** [comment]
Also make sure the locale data is actually installed by looking for it in `locale -a` output.

**Comment by dmedvinsky** [comment]
Assuming the OP gave up gsimplecal and my negligence cost us a user. Feel free to reopen, but #40 has identical issue and was resolved via gsimplecal+OS locales configuration.

**Comment by KaffeMyers** [comment]
Thanks Dmedvinsky!

I'm just a scatter brain, is all. Thank you for the assistance.  :]
