### ISSUE TITLE
Configurable first day of week

### ISSUE THREAD

**Issue by merwok** [dmedvinsky/gsimplecal#40]
Hello!  It would be useful to have an option for first day of week (or determine it automatically from locale, but I don’t know if that’s possible).  In France for example Monday is the start of the week.

With Orage being abandoned, gsimplecal is now the only small, GTK-only calendar app for Debian and derived systems.

**Comment by dglava** [comment]
That's weird, because it's taking into account the first day of the week according to the locale. Try `LC_MESSAGES=fr gsimplecal` and see if that displays the desired results.

**Comment by merwok** [comment]
I use locale fr_CA.UTF-8 and don’t have all other variants installed.

Trying with fr, fr_FR or fr_CA gets:
> (process:3524217): Gtk-WARNING **: Locale not supported by C library.	Using the fallback 'C' locale.

fr_CA.UTF-8 gets the days translated, but sunday is first.

**Comment by dmedvinsky** [comment]
@dglava is right, it should work automatically. But locales are kinda complex, there are multiple environment variables to deal with. There's `LANGUAGE`, a bunch of `LC_*` and `LANG`, each with their own priority. And the one of `LC_` ones that affects the dates and times is, I think, `LC_TIME`, not `LC_MESSAGES`.

First of all, try executing `locale` and see what it shows in the output, please.

**Comment by merwok** [comment]
LANG and all LC_ variables are set to `fr_CA.UTF-8`; LANGUAGE is `fr_CA:fr`; LC_ALL is empty.

**Comment by dmedvinsky** [comment]
Well, what does `locale -k LC_TIME` say, then? `first_weekday` line is the one we are interested in, I think.

**Comment by merwok** [comment]
```
day="dimanche;lundi;mardi;mercredi;jeudi;vendredi;samedi"
first_weekday=1
first_workday=2
```

so if that is counting from 0, it means the week stars on sunday?!

**Comment by merwok** [comment]
I have updated my locale config to use fr_FR.UTF-8 for LC_TIME.  Thanks for the help!

**Comment by dmedvinsky** [comment]
Yeah, according to `man nl_langinfo`, `DAY_1` is hardcoded to be a Sunday.

**Comment by merwok** [comment]
Sorry I don’t understand that message!
The start of week is not hard-coded (I forgot to mention that explicitly in my previous message, now edited).

**Comment by dmedvinsky** [comment]
Yeah, sorry for being vague. I mean that if the `locale -k LC_TIME` says that first weekday is `1`, that always means Sunday, regardless of other keys, because `DAY_1` is a constant meaning Sunday.
