### ISSUE TITLE
Copied the config file.  Calendar now keeps appearing on the far left

### ISSUE THREAD

**Issue by mark761** [dmedvinsky/gsimplecal#41]
I don't know which parameter to change to put it back under the clock where I want it.  Help.

**Comment by dmedvinsky** [comment]
There are three main options regarding the positioning: `mainwindow_position`, `mainwindow_xoffset`, `mainwindow_yoffset`. Although there are others that may affect the behaviour depending on the window manager you use.

As I don't know anything about your setup, I can't tell what the config should look like exactly, but there's a decent description of the options in `man gsimplecal`, so you should check that.

Hopefully, that helps.
