### ISSUE TITLE
Wiki suggestion

### ISSUE THREAD

**Issue by piotr-marendowski** [dmedvinsky/gsimplecal#51]
Would it be a good idea to add to wiki in configuration section example of how to open gsimplecal every time in fixed position?
I made it work with:
```
mainwindow_position = none
mainwindow_xoffset = 1642
mainwindow_yoffset = 0
```
![image](https://user-images.githubusercontent.com/37738748/217632157-06b60ed3-69eb-4728-9784-c9378094ab44.png)

**Comment by dmedvinsky** [comment]
When you use `mainwindow_position = none`, it's up to your window manager to place the window. If this worked for you, it doesn't mean it will work in another window manager, so this isn't a generic solution that should be documented. The rest is documented in the man page.

Thanks for suggestion though.
