### ISSUE TITLE
Configuration options for colours and fonts

### ISSUE THREAD

**Issue by nathanzachary** [dmedvinsky/gsimplecal#56]
Hello,

I have recently written a gsimplecal ebuild for Gentoo Linux, and use the application in conjunction with my tint2 toolbar.  Two configuration options that would be nice would be colours (fonts and background) and font choice.  The former would allow users to switch to a dark background and light font colour.  The latter would allow users to choose a font that more readily goes with their WM theme.

Thank you for your excellent application.  The current configuration options allow me to use it as a "world clock" of sorts by disabling the calendar portion.  I appreciate that configurability.

Cheers,
Nathan Zachary

**Comment by dmedvinsky** [comment]
Hello.

Please take a look at somewhat dupes #28 and #30.

In short, it uses GTK theme for styling, which is possible to override if one requires.
